package main;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 * Entry class and GUI
 *
 * @author David C
 */
public class GUI extends JFrame {

    // Program details
    public static final String PROGRAM = "JavaYTD";
    public static final double VERSION = 1.2;

    // Main objects
    private static Code code;
    public static GUI gui;

    /**
     * Main method entry point
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Set look and feel
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            System.err.print(e.toString());
            System.exit(1);
        }

        // Create GUI
        java.awt.EventQueue.invokeLater(() -> {
            try {
                // Initialize GUI
                gui = new GUI();
                gui.setVisible(true);
                gui.setTitle(PROGRAM + " V" + VERSION + " - by David C, 2020");
                Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
                int frameXPos = ((int) screen.getWidth() / 2) - (gui.getWidth() / 2);
                gui.setLocation(frameXPos, 39);
                gui.setResizable(false);
                gui.setDefaultCloseOperation(EXIT_ON_CLOSE);

                // Initialize code
                code = new Code();

            } catch (HeadlessException e) {
                System.err.print(e.toString());
                System.exit(1);
            }
        });
    }

    /**
     * Retrieve a component by its name
     *
     * @param nameQuery The wanted component's name
     * @return
     */
    public Component getComponentByName(String nameQuery) {

        // Return variable
        Component comp = null;

        // Get all components
        JRootPane jrp = (JRootPane) gui.getComponents()[0];
        Container cp = (Container) jrp.getContentPane();
        JPanel jp = (JPanel) cp.getComponents()[0];
        Component[] parts = jp.getComponents();

        // Iterate over all parts
        for (Component curComp : parts) {

            // When name matches, save and stop
            if (nameQuery.equalsIgnoreCase(curComp.getName())) {
                comp = curComp;
                break;
            }
        }

        // Return component
        return comp;
    }

    /**
     * Creates GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JMenuBar jMenuBar2 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JMenuBar jMenuBar3 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu1 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu2 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu5 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar4 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu6 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu7 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar5 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu8 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu9 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar6 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu11 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu12 = new javax.swing.JMenu();
        javax.swing.JMenuBar jMenuBar7 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu13 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu14 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem5 = new javax.swing.JMenuItem();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel title = new javax.swing.JLabel();
        javax.swing.JButton downloadBut = new javax.swing.JButton();
        javax.swing.JLabel urlLabel = new javax.swing.JLabel();
        javax.swing.JCheckBox exitCheckbox = new javax.swing.JCheckBox();
        javax.swing.JTextField urlField = new javax.swing.JTextField();
        javax.swing.JLabel outLabel = new javax.swing.JLabel();
        javax.swing.JButton parseBut = new javax.swing.JButton();
        javax.swing.JComboBox<String> formatCB = new javax.swing.JComboBox<>();
        javax.swing.JButton resetBut = new javax.swing.JButton();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu sitesMenu = new javax.swing.JMenu();
        javax.swing.JMenu readmeMenu = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenu11.setText("File");
        jMenuBar6.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar6.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar7.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar7.add(jMenu14);

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 450));

        panel.setBackground(new java.awt.Color(255, 255, 204));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setName("panel"); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(800, 450));

        title.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("JavaYTD");
        title.setName("title"); // NOI18N

        downloadBut.setBackground(new java.awt.Color(255, 51, 51));
        downloadBut.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        downloadBut.setForeground(new java.awt.Color(0, 0, 0));
        downloadBut.setText("Download");
        downloadBut.setToolTipText("");
        downloadBut.setAlignmentY(0.0F);
        downloadBut.setBorder(null);
        downloadBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        downloadBut.setEnabled(false);
        downloadBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downloadBut.setIconTextGap(0);
        downloadBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        downloadBut.setName("downloadBut"); // NOI18N
        downloadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButAction(evt);
            }
        });

        urlLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        urlLabel.setForeground(new java.awt.Color(0, 0, 0));
        urlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urlLabel.setText("URL");
        urlLabel.setName("urlLabel"); // NOI18N

        exitCheckbox.setBackground(new java.awt.Color(51, 51, 51));
        exitCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitCheckbox.setForeground(new java.awt.Color(0, 0, 0));
        exitCheckbox.setSelected(true);
        exitCheckbox.setText("Exit When Done");
        exitCheckbox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exitCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitCheckbox.setIconTextGap(8);
        exitCheckbox.setName("exitCheckbox"); // NOI18N

        urlField.setBackground(new java.awt.Color(255, 255, 255));
        urlField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        urlField.setForeground(new java.awt.Color(0, 0, 0));
        urlField.setName("URLfield"); // NOI18N
        urlField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                urlFieldFocusGained(evt);
            }
        });

        outLabel.setBackground(new java.awt.Color(0, 0, 0));
        outLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        outLabel.setForeground(new java.awt.Color(0, 0, 0));
        outLabel.setText("Output:");
        outLabel.setName("outLabel"); // NOI18N

        parseBut.setBackground(new java.awt.Color(255, 153, 51));
        parseBut.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        parseBut.setForeground(new java.awt.Color(0, 0, 0));
        parseBut.setToolTipText("");
        parseBut.setAlignmentY(0.0F);
        parseBut.setBorder(null);
        parseBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        parseBut.setEnabled(false);
        parseBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parseBut.setIconTextGap(0);
        parseBut.setLabel("Parse");
        parseBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        parseBut.setName("parseBut"); // NOI18N
        parseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseButActionPerformed(evt);
            }
        });

        formatCB.setBackground(new java.awt.Color(255, 255, 102));
        formatCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        formatCB.setForeground(new java.awt.Color(0, 0, 0));
        formatCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formatCB.setEnabled(false);
        formatCB.setName("formatCB"); // NOI18N
        formatCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatCBFocusGained(evt);
            }
        });

        resetBut.setBackground(new java.awt.Color(102, 255, 153));
        resetBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetBut.setForeground(new java.awt.Color(0, 0, 0));
        resetBut.setText("Reset");
        resetBut.setToolTipText("");
        resetBut.setAlignmentY(0.0F);
        resetBut.setBorder(null);
        resetBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetBut.setIconTextGap(0);
        resetBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        resetBut.setName("resetBut"); // NOI18N
        resetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(parseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(downloadBut, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelLayout.createSequentialGroup()
                                            .addComponent(exitCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(resetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(panelLayout.createSequentialGroup()
                                    .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(formatCB, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitCheckbox)
                    .addComponent(resetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadBut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(null);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sitesMenu.setBackground(new java.awt.Color(255, 255, 255));
        sitesMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sitesMenu.setForeground(new java.awt.Color(0, 0, 0));
        sitesMenu.setText("Supported Sites");
        sitesMenu.setMaximumSize(new java.awt.Dimension(140, 32767));
        sitesMenu.setName("sitesMenu"); // NOI18N
        sitesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sitesMenuClick(evt);
            }
        });
        jMenuBar1.add(sitesMenu);

        readmeMenu.setBackground(new java.awt.Color(255, 255, 255));
        readmeMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        readmeMenu.setForeground(new java.awt.Color(0, 0, 0));
        readmeMenu.setText("youtube-dl Readme");
        readmeMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        readmeMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        readmeMenu.setMaximumSize(new java.awt.Dimension(140, 32767));
        readmeMenu.setName("readmeMenu"); // NOI18N
        readmeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readmeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(readmeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When download button is pressed, process options
     *
     * @param evt
     */
    private void downloadButAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButAction

        // Process options
        code.processDwlReq();
    }//GEN-LAST:event_downloadButAction

    /**
     * When URL field gains focus, extract data from clipboard automatically,
     * and enable parse button
     *
     * @param evt
     */
    private void urlFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlFieldFocusGained
        try {

            // Get clipboard string
            String data = (String) Toolkit.getDefaultToolkit()
                    .getSystemClipboard().getData(DataFlavor.stringFlavor);

            // Get textfield and change text
            JTextField txtField = (JTextField) evt.getSource();
            txtField.setText(data);

            // Enable parse button
            GUI.gui.getParseBut().setEnabled(true);

        } catch (UnsupportedFlavorException | IOException ex) {

            // Log only and do NOT quit
            System.out.println("Clipboard error\n");
        }
    }//GEN-LAST:event_urlFieldFocusGained

    /**
     * When sites menu is clicked, open supported sites page
     *
     * @param evt
     */
    private void sitesMenuClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitesMenuClick

        // Open supported sites URL
        String sites;
        sites = "https://github.com/ytdl-org/youtube-dl/";
        sites += "blob/master/docs/supportedsites.md";
        code.openURL(sites);
    }//GEN-LAST:event_sitesMenuClick

    /**
     * Parse URL given
     *
     * @param evt
     */
    private void parseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseButActionPerformed

        // Parse URL
        code.parseURL();
    }//GEN-LAST:event_parseButActionPerformed

    /**
     * When format selector gains focus, enable download button
     *
     * @param evt
     */
    private void formatCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatCBFocusGained

        // Enable download button
        getDownloadBut().setEnabled(true);
    }//GEN-LAST:event_formatCBFocusGained

    /**
     * Reset button action
     *
     * @param evt
     */
    private void resetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButActionPerformed

        // Reset URL field
        getURLField().setText("");

        // Enable parse button
        getParseBut().setEnabled(true);

        // Remove format options and disable format selector
        JComboBox formatCB = getFormatCB();
        formatCB.removeAllItems();
        formatCB.setEnabled(false);

        // Disable download button
        getDownloadBut().setEnabled(false);

        // Reset output label
        setOutputLabel("");
    }//GEN-LAST:event_resetButActionPerformed

    /**
     * When readme menu clicked, open readme page
     *
     * @param evt
     */
    private void readmeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readmeMenuMouseClicked

        // Open readme URL
        String readme;
        readme = "https://github.com/ytdl-org/youtube-dl/";
        readme += "blob/master/README.md";
        code.openURL(readme);
    }//GEN-LAST:event_readmeMenuMouseClicked

    /**
     * Set output field
     *
     * @param newOutput
     */
    public void setOutputLabel(String newOutput) {

        // Get label
        JLabel outLabel;
        outLabel = (JLabel) GUI.gui.getComponentByName("outLabel");

        // Set text
        outLabel.setText("Output: " + newOutput);
    }

    /**
     * Get URL text field
     *
     * @return
     */
    public JTextField getURLField() {
        return (JTextField) getComponentByName("urlField");
    }

    /**
     * Get format combo box
     *
     * @return
     */
    public JComboBox getFormatCB() {
        return (JComboBox) getComponentByName("formatCB");
    }

    /**
     * Get download button
     *
     * @return
     */
    public JButton getDownloadBut() {
        return (JButton) getComponentByName("downloadBut");
    }

    /**
     * Get parse button
     *
     * @return
     */
    public JButton getParseBut() {
        return (JButton) getComponentByName("parseBut");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
