package main;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Pattern;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 * Entry class and GUI
 *
 * @author David C
 */
public class GUI extends JFrame {

    // Program details
    public static final String PROGRAM = "JavaYTD";
    public static final double VERSION = 1.3;

    // Main objects
    public static Code code;
    public static GUI gui;

    // Timer
    private static Timer timer;

    /**
     * Main method entry point
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Set look and feel
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            System.err.print(e.toString());
            System.exit(1);
        }

        // Initialize GUI
        try {
            gui = new GUI();
            gui.setVisible(true);
            gui.setTitle(PROGRAM + " V" + VERSION + " - by David C, 2020");
            Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
            int frameXPos = ((int) screen.getWidth() / 2) - (gui.getWidth() / 2);
            gui.setLocation(frameXPos, 15);
            gui.setResizable(false);
            gui.setDefaultCloseOperation(EXIT_ON_CLOSE);
        } catch (HeadlessException e) {
            System.err.print(e.toString());
            System.exit(1);
        }

        // Initialize code
        code = new Code();

        // Initialize timer
        timer = new Timer();
    }

    /**
     * Retrieve a component by its name
     *
     * @param nameQuery The wanted component's name
     * @return
     */
    public Component getComponentByName(String nameQuery) {

        // Return variable
        Component comp = null;

        // Get all components
        JRootPane jrp = (JRootPane) gui.getComponents()[0];
        Container cp = (Container) jrp.getContentPane();
        JPanel jp = (JPanel) cp.getComponents()[0];
        Component[] parts = jp.getComponents();

        // Iterate over all parts
        for (Component curComp : parts) {

            // When name matches, save and stop
            if (nameQuery.equalsIgnoreCase(curComp.getName())) {
                comp = curComp;
                break;
            }
        }

        // Return component
        return comp;
    }

    /**
     * Creates GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel title = new javax.swing.JLabel();
        javax.swing.JButton downloadBut = new javax.swing.JButton();
        javax.swing.JLabel outputLabel = new javax.swing.JLabel();
        javax.swing.JCheckBox exitCheckbox = new javax.swing.JCheckBox();
        javax.swing.JTextField urlField = new javax.swing.JTextField();
        javax.swing.JButton parseBut = new javax.swing.JButton();
        javax.swing.JComboBox<String> formatCB = new javax.swing.JComboBox<>();
        javax.swing.JButton resetBut = new javax.swing.JButton();
        javax.swing.JLabel formatLabel = new javax.swing.JLabel();
        javax.swing.JLabel urlLabel = new javax.swing.JLabel();
        javax.swing.JScrollPane outputSP = new javax.swing.JScrollPane();
        javax.swing.JTextArea outputTA = new javax.swing.JTextArea();
        javax.swing.JButton exportBut = new javax.swing.JButton();
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu sitesMenu = new javax.swing.JMenu();
        javax.swing.JMenu readmeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 450));

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setName("panel"); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(800, 450));

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("JavaYTD");
        title.setName("title"); // NOI18N

        downloadBut.setBackground(new java.awt.Color(255, 102, 102));
        downloadBut.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        downloadBut.setForeground(new java.awt.Color(0, 0, 0));
        downloadBut.setText("Download");
        downloadBut.setToolTipText("");
        downloadBut.setAlignmentY(0.0F);
        downloadBut.setBorder(null);
        downloadBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        downloadBut.setEnabled(false);
        downloadBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downloadBut.setIconTextGap(0);
        downloadBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        downloadBut.setName("downloadBut"); // NOI18N
        downloadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButAction(evt);
            }
        });

        outputLabel.setBackground(new java.awt.Color(0, 0, 0));
        outputLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(255, 255, 255));
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputLabel.setText("Output");
        outputLabel.setMaximumSize(new java.awt.Dimension(60, 25));
        outputLabel.setMinimumSize(new java.awt.Dimension(60, 25));
        outputLabel.setName("outputLabel"); // NOI18N
        outputLabel.setPreferredSize(new java.awt.Dimension(60, 25));

        exitCheckbox.setBackground(new java.awt.Color(0, 0, 0));
        exitCheckbox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitCheckbox.setForeground(new java.awt.Color(255, 255, 255));
        exitCheckbox.setText("Exit When Done");
        exitCheckbox.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        exitCheckbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitCheckbox.setIconTextGap(8);
        exitCheckbox.setName("exitCheckbox"); // NOI18N

        urlField.setBackground(new java.awt.Color(255, 255, 255));
        urlField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        urlField.setForeground(new java.awt.Color(0, 0, 0));
        urlField.setEnabled(false);
        urlField.setName("URLfield"); // NOI18N
        urlField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                urlFieldFocusGained(evt);
            }
        });

        parseBut.setBackground(new java.awt.Color(255, 204, 102));
        parseBut.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        parseBut.setForeground(new java.awt.Color(0, 0, 0));
        parseBut.setToolTipText("");
        parseBut.setAlignmentY(0.0F);
        parseBut.setBorder(null);
        parseBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        parseBut.setEnabled(false);
        parseBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parseBut.setIconTextGap(0);
        parseBut.setLabel("Parse");
        parseBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        parseBut.setName("parseBut"); // NOI18N
        parseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parseButActionPerformed(evt);
            }
        });

        formatCB.setBackground(new java.awt.Color(255, 255, 102));
        formatCB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        formatCB.setForeground(new java.awt.Color(0, 0, 0));
        formatCB.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        formatCB.setEnabled(false);
        formatCB.setName("formatCB"); // NOI18N
        formatCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formatCBFocusGained(evt);
            }
        });

        resetBut.setBackground(new java.awt.Color(153, 153, 255));
        resetBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetBut.setForeground(new java.awt.Color(0, 0, 0));
        resetBut.setText("Reset");
        resetBut.setToolTipText("");
        resetBut.setAlignmentY(0.0F);
        resetBut.setBorder(null);
        resetBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetBut.setEnabled(false);
        resetBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetBut.setIconTextGap(0);
        resetBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        resetBut.setName("resetBut"); // NOI18N
        resetBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButActionPerformed(evt);
            }
        });

        formatLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        formatLabel.setForeground(new java.awt.Color(255, 255, 255));
        formatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formatLabel.setText("Format");
        formatLabel.setName("urlLabel"); // NOI18N

        urlLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        urlLabel.setForeground(new java.awt.Color(255, 255, 255));
        urlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        urlLabel.setText("URL");
        urlLabel.setName("urlLabel"); // NOI18N

        outputSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        outputSP.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        outputSP.setName("outputSP"); // NOI18N

        outputTA.setEditable(false);
        outputTA.setBackground(new java.awt.Color(51, 51, 51));
        outputTA.setColumns(20);
        outputTA.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        outputTA.setForeground(new java.awt.Color(255, 255, 255));
        outputTA.setLineWrap(true);
        outputTA.setRows(5);
        outputTA.setBorder(null);
        outputTA.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        outputTA.setFocusable(false);
        outputTA.setName("outputTA"); // NOI18N
        outputTA.setRequestFocusEnabled(false);
        outputSP.setViewportView(outputTA);
        outputTA.getAccessibleContext().setAccessibleParent(panel);

        exportBut.setBackground(new java.awt.Color(0, 204, 0));
        exportBut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exportBut.setForeground(new java.awt.Color(0, 0, 0));
        exportBut.setText("Export");
        exportBut.setToolTipText("");
        exportBut.setAlignmentY(0.0F);
        exportBut.setBorder(null);
        exportBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exportBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exportBut.setIconTextGap(0);
        exportBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        exportBut.setName("exportBut"); // NOI18N
        exportBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(downloadBut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addComponent(exitCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(formatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatCB, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(outputLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exportBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parseBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(outputSP, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                                .addComponent(urlField)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(outputSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parseBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formatCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitCheckbox)
                    .addComponent(resetBut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(downloadBut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        menuBar.setBackground(new java.awt.Color(204, 204, 204));
        menuBar.setBorder(null);
        menuBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        sitesMenu.setBackground(new java.awt.Color(255, 255, 255));
        sitesMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sitesMenu.setForeground(new java.awt.Color(0, 0, 0));
        sitesMenu.setText("Supported Sites");
        sitesMenu.setMaximumSize(new java.awt.Dimension(140, 32767));
        sitesMenu.setName("sitesMenu"); // NOI18N
        sitesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sitesMenuClick(evt);
            }
        });
        menuBar.add(sitesMenu);

        readmeMenu.setBackground(new java.awt.Color(255, 255, 255));
        readmeMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        readmeMenu.setForeground(new java.awt.Color(0, 0, 0));
        readmeMenu.setText("youtube-dl Readme");
        readmeMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        readmeMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        readmeMenu.setMaximumSize(new java.awt.Dimension(140, 32767));
        readmeMenu.setName("readmeMenu"); // NOI18N
        readmeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readmeMenuMouseClicked(evt);
            }
        });
        menuBar.add(readmeMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When sites menu is clicked, open supported sites page
     *
     * @param evt
     */
    private void sitesMenuClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sitesMenuClick

        // Open supported sites URL
        String sites;
        sites = "https://github.com/ytdl-org/youtube-dl/";
        sites += "blob/master/docs/supportedsites.md";
        code.openURL(sites);
    }//GEN-LAST:event_sitesMenuClick

    /**
     * When readme menu clicked, open readme page
     *
     * @param evt
     */
    private void readmeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readmeMenuMouseClicked

        // Open readme URL
        String readme;
        readme = "https://github.com/ytdl-org/youtube-dl/";
        readme += "blob/master/README.md";
        code.openURL(readme);
    }//GEN-LAST:event_readmeMenuMouseClicked

    /**
     * Reset button action
     *
     * @param evt
     */
    private void resetButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButActionPerformed

        // Reset URL field
        getURLField().setText("");

        // Remove format options and disable format selector
        JComboBox formatCB = getFormatCB();
        formatCB.removeAllItems();
        formatCB.setEnabled(false);

        // Disable download button
        getDownloadBut().setEnabled(false);
    }//GEN-LAST:event_resetButActionPerformed

    /**
     * When format selector gains focus, enable download button
     *
     * @param evt
     */
    private void formatCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formatCBFocusGained

        // Enable download button
        getDownloadBut().setEnabled(true);
    }//GEN-LAST:event_formatCBFocusGained

    /**
     * Parse URL given
     *
     * @param evt
     */
    private void parseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parseButActionPerformed
        // Parse URL on separate thread
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                code.parseURL(GUI.gui.getRefinedURL());
            }
        }, 5);
    }//GEN-LAST:event_parseButActionPerformed

    /**
     * When URL field gains focus, extract data from clipboard automatically,
     * and enable parse button
     *
     * @param evt
     */
    private void urlFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_urlFieldFocusGained
        try {

            // Get clipboard string
            String data = (String) Toolkit.getDefaultToolkit()
                    .getSystemClipboard().getData(DataFlavor.stringFlavor);

            // Get textfield and change text
            JTextField txtField = (JTextField) evt.getSource();
            txtField.setText(data);

            // Enable parse button
            GUI.gui.getParseBut().setEnabled(true);

        } catch (UnsupportedFlavorException | IOException ex) {

            // Log only and do NOT quit
            System.out.println("Clipboard error\n");
        }
    }//GEN-LAST:event_urlFieldFocusGained

    /**
     * When download button is pressed, process download request
     *
     * @param evt
     */
    private void downloadButAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButAction
        // Process download request on separate thread
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                code.processDwlReq(GUI.gui.getRefinedURL());
            }
        }, 5);
    }//GEN-LAST:event_downloadButAction

    private void exportButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportButActionPerformed

    /**
     * Update output by appending string to output text area
     *
     * @param outputS
     * @param newLine
     */
    public void updateOutput(String outputS, boolean newLine) {

        // Get output
        JTextArea output = getOutputTA();

        // If new line wanted
        if (newLine) {

            // Add new line
            outputS += "\n";
        }

        // Append line to output text area
        output.append(outputS);

        // Scroll to newest line
        output.setCaretPosition(output.getDocument().getLength());
    }

    /**
     * Get output text area
     *
     * @return
     */
    private JTextArea getOutputTA() {

        // Get scroll pane
        JScrollPane jsp;
        jsp = (JScrollPane) GUI.gui.getComponentByName("outputSP");

        // Extract text area
        JTextArea jta;
        jta = (JTextArea) jsp.getViewport().getComponents()[0];

        // Return text area
        return jta;
    }

    /**
     * Return the status of a given checkbox
     *
     * @param checkBoxName
     * @return
     */
    public boolean getCheckboxStatus(String checkBoxName) {

        // Get checkbox
        JCheckBox checkBox;
        checkBox = (JCheckBox) GUI.gui.getComponentByName(checkBoxName);

        // Return status of checkbox
        return checkBox.isSelected();
    }

    /**
     * Get only important part of URL
     *
     * @return
     */
    public String getRefinedURL() {

        // Get raw URL string
        String rawURL = GUI.gui.getURLField().getText();

        // If URL contains ampersand
        if (rawURL.contains("&")) {

            // Refine, notify and return
            return refineURLtype(rawURL, "&");

        } else if (rawURL.contains("?list=")) {

            // Refine, notify and return
            return refineURLtype(rawURL, "?list=");
        } else {

            // Otherwise, return raw URL
            return rawURL;
        }
    }

    /**
     * Refine URL
     *
     * @param rawURL
     * @return
     */
    private String refineURLtype(String rawURL, String splitS) {

        // Get split pattern
        String pattern = Pattern.quote(splitS);

        // Split up by ampersand
        String[] URLparts = rawURL.split(pattern);

        // Extract first part
        String refinedURL = URLparts[0];

        // Notify
        GUI.code.notifyln("\nRefined URL to: " + refinedURL);

        // Return refined URL
        return refinedURL;
    }

    /**
     * Get URL text field
     *
     * @return
     */
    public JTextField getURLField() {
        return (JTextField) getComponentByName("urlField");
    }

    /**
     * Get format combo box
     *
     * @return
     */
    public JComboBox getFormatCB() {
        return (JComboBox) getComponentByName("formatCB");
    }

    /**
     * Get download button
     *
     * @return
     */
    public JButton getDownloadBut() {
        return (JButton) getComponentByName("downloadBut");
    }

    /**
     * Get parse button
     *
     * @return
     */
    public JButton getParseBut() {
        return (JButton) getComponentByName("parseBut");
    }

    /**
     * Get reset button
     *
     * @return
     */
    public JButton getResetBut() {
        return (JButton) getComponentByName("resetBut");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
